sudo: required

language: node_js

node_js:
  - "8.9.1"

jdk:
  - oraclejdk8

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - oracle-java8-set-default
  postgresql: '9.3'

before_install:
 - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.4.0.deb && sudo dpkg -i --force-confnew elasticsearch-5.4.0.deb
 - sudo apt-get install -y postgresql-9.3-postgis-2.3 gdal-bin proj-bin libgeos-dev libgeos++-dev libproj-dev
 - export JAVA_HOME='/usr'
 - sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-kuromoji
 - sudo service elasticsearch start

before_script:
  - cp config.js.travis config.js
  - psql -c 'create database inaturalist_test;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d inaturalist_test
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d inaturalist_test
  - psql -f schema/database.sql -U postgres -d inaturalist_test
  - touch vision-taxa.txt
  - sleep 15

after_script:
  - npm run coveralls

notifications:
  slack:
    secure: ssW+kf5ZQudczXshwoLxSWkGrnYT7CNT9gIz1WPS6K4CHQM9WsuxZmF3bjdElV/huvhNmY0Ed2i1ByMzhcZdmgRxbbUyRfMpA2bnxILWKGvH4DAV8iFxI1VSzCIFhW9BMTbhgVoSLpVseETxtBJMkZYOL6Vmr8XRWFBTB969wCKEH6g5nRk3Q7g0F2d+AE7Tug9fPukurYBzX38rgyRQllIGrp2rCsUb4q4KoQoo26bGRpF2d80BS7fUS7Vk8FbkumD2FbuXzGweHfq8K647kbVu7zTqOAw1KfGy/c7JGwiqxr0+JM26RzJczUdM6Kral9qkPVGbyGkT1YgEOh8IvIlO0SQppEvQQhG6vl+qpobdI+zoDgxQISi+YiCJiOHG70bCmSh0GoiOHk9TMDRTSGGj3HfGK4p4xb6gg7KaTj2GcWcq31V6BuLlJuX03nj0wgSwUmEVicO+9soi4lT+CDp9ZoO3X9y/p8nO3nkbicZcuIWfBBmQrBxwl+nXlwrKGLC03SX7QuqVsvT/nuJBHSudC1kVuVLh+f3TuaCoyND9RyiVu0eVB1pFZ7Zq84XJIUp6u7AcJR8yVJozI0DZiyIj42Zumpe5f3lNy6UG9o+UBRkdnfk+zh3vMVupf0eEqaB05MyLBDyzD0LUQVsMKHdmCXvWCtJMZ3qIkQFgcS4=

