language: node_js

compiler: gcc

node_js:
  - "0.12"
  - "0.10"

services:
  - elasticsearch

addons:
  postgresql: "9.3"

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-4.7 g++-4.7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.7 20
  - g++ --version
  - sudo apt-get update -qq

before_script:
  - cp config.js.travis config.js
  - sleep 15

