sudo: required

dist: xenial

language: node_js

node_js:
  - 12.13.0

jdk:
  - openjdk8

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  postgresql: "10"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y postgresql-10-postgis-2.4 gdal-bin proj-bin libgeos-dev libgeos++-dev libproj-dev
  - psql -U postgres -c "create extension postgis"
  - psql -U postgres -c 'create extension "uuid-ossp"'
  - createdb -O postgres template_postgis
  - psql -U postgres template_postgis -c "UPDATE pg_database SET datistemplate = TRUE WHERE datname = 'template_postgis'"
  - export JAVA_HOME='/usr'
  - curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.3.1-linux-x86_64.tar.gz | tar xz -C /tmp
  - /tmp/elasticsearch-7.3.1/bin/elasticsearch-keystore create
  - /tmp/elasticsearch-7.3.1/bin/elasticsearch-plugin install analysis-kuromoji
  - /tmp/elasticsearch-7.3.1/bin/elasticsearch -E http.port=9200 -d

before_script:
  - cp config.js.travis config.js
  - psql -c 'create database inaturalist_test;' -U postgres
  - psql -f schema/database.sql -U postgres -d inaturalist_test
  - touch vision-taxa.txt
  - sleep 30

after_script:
  - npm run coveralls

notifications:
  slack:
    secure: ssW+kf5ZQudczXshwoLxSWkGrnYT7CNT9gIz1WPS6K4CHQM9WsuxZmF3bjdElV/huvhNmY0Ed2i1ByMzhcZdmgRxbbUyRfMpA2bnxILWKGvH4DAV8iFxI1VSzCIFhW9BMTbhgVoSLpVseETxtBJMkZYOL6Vmr8XRWFBTB969wCKEH6g5nRk3Q7g0F2d+AE7Tug9fPukurYBzX38rgyRQllIGrp2rCsUb4q4KoQoo26bGRpF2d80BS7fUS7Vk8FbkumD2FbuXzGweHfq8K647kbVu7zTqOAw1KfGy/c7JGwiqxr0+JM26RzJczUdM6Kral9qkPVGbyGkT1YgEOh8IvIlO0SQppEvQQhG6vl+qpobdI+zoDgxQISi+YiCJiOHG70bCmSh0GoiOHk9TMDRTSGGj3HfGK4p4xb6gg7KaTj2GcWcq31V6BuLlJuX03nj0wgSwUmEVicO+9soi4lT+CDp9ZoO3X9y/p8nO3nkbicZcuIWfBBmQrBxwl+nXlwrKGLC03SX7QuqVsvT/nuJBHSudC1kVuVLh+f3TuaCoyND9RyiVu0eVB1pFZ7Zq84XJIUp6u7AcJR8yVJozI0DZiyIj42Zumpe5f3lNy6UG9o+UBRkdnfk+zh3vMVupf0eEqaB05MyLBDyzD0LUQVsMKHdmCXvWCtJMZ3qIkQFgcS4=

